version: '3.0'
services:
   mongodb:
     container_name: mongodb
     build:
       context: .
       dockerfile: Dockerfile-mongo
     image: mongodb:1.0.0
     ports:
       - "27017:27017"
     restart: always

   app:
     container_name: app
     build:
       context: .
       dockerfile: Dockerfile-app
     image: myapp:1.0.0
     links:
       - mongodb:mongodb
