version: '3.0'
services:
  testmongo1:
     container_name: testmongo1
     build:
       context: .
       dockerfile: Dockerfile
     image: mongodb:1.0.0
     ports:
       - "27017:27017"
     restart: always

  testapp1:
     container_name: testapp1
     build:
       context: .
       dockerfile: Dockerfile-app
     image: myapp:1.0.0
     ports:
       - "8111:8111"
     links:
       - testmongo1:testmongo1
